server:
  port: 8083

spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    username: root
    password: kaca
    url: jdbc:mysql://localhost:3306/new
    driver-class-name: com.mysql.cj.jdbc.Driver

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: password
    realmImportFile: aes-realm.json

